import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os


st.set_page_config(
    page_title="Math Score Predictor",
    page_icon="🎓",
    layout="centered"
)

# Clean up default button padding and general container styling
st.markdown("""
<style>
    .stButton>button {
        width: 100%;
        border-radius: 8px;
        font-weight: 600;
        background-color: #2E86C1;
        color: white;
        padding: 0.5rem 1rem;
        transition: all 0.3s;
    }
    .stButton>button:hover {
        background-color: #1B4F72;
        color: white;
    }
    .main-header {
        font-size: 2.8rem;
        color: #2E86C1;
        text-align: center;
        margin-bottom: 5px;
        font-weight: 700;
    }
    .sub-header {
        text-align: center;
        color: #7F8C8D;
        margin-bottom: 30px;
        font-size: 1.1rem;
    }
    .prediction-box {
        background-color: #E8F8F5;
        border-left: 5px solid #1ABC9C;
        padding: 20px;
        border-radius: 5px;
        margin-top: 20px;
        text-align: center;
    }
</style>
""", unsafe_allow_html=True)


st.markdown('<p class="main-header">🎓 Math Score Predictor</p>', unsafe_allow_html=True)
st.markdown('<p class="sub-header">Enter a student\'s demographics and current academic standing below to predict their final math score.</p>', unsafe_allow_html=True)


@st.cache_resource
def load_application_model():
    """Load the best available trained predictor model."""
    model_dir = "models"
    # Prefer Decision Tree over Linear Regression if both exist
    preferences = ["Decision_Tree.joblib", "Linear_Regression.joblib"]
    
    for pref in preferences:
        path = os.path.join(model_dir, pref)
        if os.path.exists(path):
            return joblib.load(path), pref.split('.')[0].replace('_', ' ')
            
    return None, None


model, model_name = load_application_model()

if model is None:
    st.warning("⚠️ **No trained models found!** \n\nPlease run the training script (`python src/models/train.py`) to generate `.joblib` files first.")
    st.stop()
else:
    st.caption(f"🚀 Currently using: **{model_name}** engine")


st.markdown("### 📋 Student Demographics")
col1, col2 = st.columns(2)

with col1:
    gender = st.selectbox("Gender", ["female", "male"])
    race_ethnicity = st.selectbox("Race/Ethnicity", ["group A", "group B", "group C", "group D", "group E"])
    lunch = st.selectbox("Lunch Plan", ["standard", "free/reduced"])

with col2:
    parental_education = st.selectbox(
        "Parental Education Level", 
        ["high school", "some high school", "some college", "associate's degree", "bachelor's degree", "master's degree"]
    )
    test_preparation = st.selectbox("Test Prep Course", ["none", "completed"])


st.markdown("---")
st.markdown("### 📊 Current Academic Standings")
col3, col4 = st.columns(2)

with col3:
    reading_score = st.slider("Reading Score", min_value=0, max_value=100, value=70)
with col4:
    writing_score = st.slider("Writing Score", min_value=0, max_value=100, value=70)

st.markdown("<br>", unsafe_allow_html=True)

if st.button("Predict Expected Math Score"):
    
    # Bundle user inputs for preprocessing
    raw_input_df = pd.DataFrame({
        'gender': [gender],
        'race/ethnicity': [race_ethnicity],
        'parental level of education': [parental_education],
        'lunch': [lunch],
        'test preparation course': [test_preparation],
        'reading score': [reading_score],
        'writing score': [writing_score]
    })
    
    # One-hot encode the raw input so it behaves correctly in standard scikit-learn models
    encoded_input = pd.get_dummies(raw_input_df)
    
    try:
        # Align input columns perfectly with how the model was trained
        # This resolves missing column bugs generated by applying get_dummies to a single row
        expected_training_cols = model.feature_names_in_
        final_input_df = encoded_input.reindex(columns=expected_training_cols, fill_value=0)
        
        predicted_score = model.predict(final_input_df)[0]
        predicted_score = np.clip(predicted_score, 0, 100)
        
        st.markdown(f"""
        <div class="prediction-box">
            <h2 style="color: #1ABC9C; margin:0px;">{predicted_score:.1f} / 100</h2>
            <p style="margin: 0px; color: #7F8C8D;">Predicted Math Score Expected</p>
        </div>
        """, unsafe_allow_html=True)
        
        if predicted_score >= 90:
            st.balloons()
            
    except AttributeError:
        st.error("Model format mismatch: Expected `feature_names_in_` property. Consider retraining.")
